import numpy as np
import site
import os
from pathlib import Path
import shelve
from tqdm import tqdm
import requests
import mendeleev
import materials_compendium as mc
import pandas as pd

# Constants
SPEED_OF_LIGHT = 299792458  # m/s
MASS_OF_NEUTRON = 939.56542052 * 1e6 / (SPEED_OF_LIGHT ** 2)  # [eV s²/m²]


def time2energy(time, flight_path_length):
    """
    Convert time-of-flight to energy of the neutron.

    Parameters:
    time (float): Time-of-flight in seconds.
    flight_path_length (float): Flight path length in meters.

    Returns:
    float: Energy of the neutron in electronvolts (eV).
    """
    γ = 1 / np.sqrt(1 - (flight_path_length / time) ** 2 / SPEED_OF_LIGHT ** 2)
    return (γ - 1) * MASS_OF_NEUTRON * SPEED_OF_LIGHT ** 2  # eV

def energy2time(energy, flight_path_length):
    """
    Convert energy to time-of-flight of the neutron.

    Parameters:
    energy (float): Energy of the neutron in electronvolts (eV).
    flight_path_length (float): Flight path length in meters.

    Returns:
    float: Time-of-flight in seconds.
    """
    γ = 1 + energy / (MASS_OF_NEUTRON * SPEED_OF_LIGHT ** 2)
    return flight_path_length / SPEED_OF_LIGHT * np.sqrt(γ ** 2 / (γ ** 2 - 1))

def materials_dict():
    """
    Generate a dictionary containing information about materials, including their densities, 
    atomic densities, chemical formulas, and elemental/isotopic compositions.

    The function retrieves material data from the MaterialsCompendium package and organizes 
    it into a dictionary. Each material's total mass is calculated based on the atomic weights 
    and weight fractions of its constituent elements. The mass of each element reflects its 
    actual atomic mass, and the total mass is weighted by element fractions.

    Returns:
        materials (dict): A dictionary containing information for each material.
            Example structure:
            {
                'MaterialName': {
                    'name': 'MaterialName',
                    'density': <density>,  # g/cm³
                    'n': <atomic_density>,  # atoms per barn
                    'mass': <total_mass>,   # total mass (g/mol)
                    'formula': 'ChemicalFormula',
                    'elements': {
                        'ElementSymbol': {
                            'weight': <weight_fraction>,
                            'mass': <element_atomic_mass>,  # Actual atomic mass of the element (g/mol)
                            'isotopes': {
                                'IsotopeName': <isotope_weight_fraction>,
                                ...
                            }
                        }
                    }
                },
                ...
            }
    """
    materials = {}

    for material in mc.MaterialsCompendium:
        mat_name = material.Name
        density = material.Density
        n = material.MaterialAtomDensity
        formula = material.Formula
        total_mass = 0.0  # Initialize total weighted mass for the material

        elements = {}

        # Process each element in the material
        for element in material.Elements:
            name = element.Element
            weight_fraction = element.WeightFraction_whole  # Whole weight fraction of the element

            # Get the actual atomic mass of the element (e.g., 12 for Carbon)
            element_atomic_mass = element.AtomicMass  # Actual atomic mass (g/mol)

            # Add element to the elements dict with its actual atomic mass
            elements[name] = {
                "weight": weight_fraction,
                "mass": element_atomic_mass  # Actual atomic mass (g/mol)
            }

            # Calculate isotopic contributions if present
            isotopes = {}
            for isotope in element.Isotopes:
                iso_name = format_isotope(isotope.Isotope)
                iso_weight = isotope.WeightFraction
                if iso_weight > 0:
                    isotopes[iso_name] = iso_weight

            # Add isotopic data to the element
            elements[name]["isotopes"] = isotopes if isotopes else None  # If no isotopes, set None

            # Update total weighted mass for the material by summing element mass contributions weighted by fraction
            total_mass += element_atomic_mass * weight_fraction

        # Store the material information with calculated total weighted mass
        materials[mat_name] = {
            "name": mat_name,
            "density": density,   # g/cm³
            "n": n,               # atoms/barn
            "mass": total_mass,    # Total molar mass (g/mol), weighted by element fractions
            "formula": formula,
            "elements": elements   # Each element has its actual atomic mass (g/mol)
        }

    return materials





def elements_and_isotopes_dict():
    """
    Generate a dictionary of elements and isotopes with details such as 
    atoms per barn, total mass, and isotopic abundances.
    
    Returns:
        elements (dict): A dictionary containing information for each element.
        isotopes (dict): A dictionary containing information for each isotope.
    """
    elements = {}
    isotopes = {}
    
    import mendeleev
    all_elements = mendeleev.get_all_elements()

    for element in all_elements:
        name = element.name
        symbol = element.symbol

        # Handle cases where density or mass is missing (None)
        if element.density is None or element.mass is None:
            # Skip the element if either value is missing
            continue
        
        # Calculate atoms per barn and total mass
        atoms_per_barn = element.density / element.mass * 0.602214076  # Atoms/barn
        total_mass = element.mass  # Atomic mass (g/mol)
        
        # Initialize element entry with name, atoms per barn, and mass
        elements[name] = {
            "name": name,
            "n": atoms_per_barn,  # atoms per barn
            "mass": total_mass,   # total atomic mass (g/mol)
            "formula": symbol,    # Element symbol (formula)
            "density": element.density,  # g/cm³
            "elements": {symbol: {"weight": 1}}
        }

        # Add isotopic data if available
        element_isotopes = {f"{element.symbol}{iso.mass_number}": iso.abundance * 0.01
                            for iso in element.isotopes if iso.abundance is not None}
        
        if element_isotopes:
            elements[name]["elements"][symbol]["isotopes"] = element_isotopes
        
        # Add isotopes to a separate dictionary
        for iso in element.isotopes:
            if iso.abundance is not None:
                iso_name = f"{element.symbol}{iso.mass_number}"
                isotopes[iso_name] = {
                    "name": iso_name,
                    "n": element.density / iso.mass * 0.602214076,  # Atoms/barn for the isotope
                    "mass": iso.mass,  # Isotope mass
                    "formula": iso_name,
                    "density": element.density,
                    "elements": {symbol: {"weight": 1, "isotopes": {iso_name: 1.0}}}
                }

    return elements, isotopes




def format_isotope(isotope_string):
    # Find where the digits start in the string
    for i, char in enumerate(isotope_string):
        if char.isdigit():
            # Split the string into element and mass number parts
            element = isotope_string[:i]
            mass_number = isotope_string[i:]
            # Return the formatted string
            return f"{element}-{mass_number}"
    # Return the original string if no digits are found
    return isotope_string

def get_cache_path():
    # Get the user's site-packages directory
    user_site = site.getusersitepackages()
    # Create a subdirectory for our cache
    cache_dir = Path(user_site) / "nbragg"
    cache_dir.mkdir(parents=True, exist_ok=True)
    return cache_dir

def load_or_create_materials_cache():
    cache_path = get_cache_path() / "materials.db"
    
    if cache_path.exists():
        with shelve.open(str(cache_path.with_suffix(""))) as fid:
            materials = fid.get("materials")
            elements = fid.get("elements")
            isotopes = fid.get("isotopes")
        
        # If the cache is incomplete, regenerate it
        if materials is None or elements is None:
            return create_and_save_materials_cache()
        
        return materials, elements, isotopes
    else:
        return create_and_save_materials_cache()

def create_and_save_materials_cache():
    materials = materials_dict()
    elements, isotopes = elements_and_isotopes_dict()
    
    cache_path = get_cache_path() / "materials"
    with shelve.open(str(cache_path)) as fid:
        fid["materials"] = materials
        fid["elements"] = elements
        fid["isotopes"] = isotopes
    
    return materials, elements, isotopes


def interpolate(df):
    # Get underlying NumPy array and index values
    arr = df.values
    x = df.index.values  # Use the index values (energy bins) for interpolation

    # Loop through each column and interpolate NaNs using the index as x
    for j in range(arr.shape[1]):
        col = arr[:, j]
        valid_mask = ~np.isnan(col)
        
        if valid_mask.sum() > 1:  # Ensure there are at least two non-NaN values
            x_valid = x[valid_mask]     # Use index values for valid data points
            y_valid = col[valid_mask]   # Non-NaN values in the column
            x_nan = x[np.isnan(col)]    # Index values where NaNs are present
            
            if len(x_nan) > 0:  # Only interpolate if NaNs exist in the column
                # Interpolate NaNs using the actual index values
                col[np.isnan(col)] = np.interp(x_nan, x_valid, y_valid)

    # Return a DataFrame with the interpolated values
    return pd.DataFrame(arr, index=df.index, columns=df.columns)


materials = {'AgBr_sg225_SilverBromide.ncmat': {'short_name': 'Silver Bromide',
  'name': 'SilverBromide',
  'formula': 'AgBr',
  'space_group': 225,
  'filename': 'AgBr_sg225_SilverBromide.ncmat',
  'density': 6.473,
  'mass': 187.77,
  'atomic_density': 0.0208},
 'Ag_sg225_Silver.ncmat': {'short_name': 'Silver',
  'name': 'Silver',
  'formula': 'Ag',
  'space_group': 225,
  'filename': 'Ag_sg225_Silver.ncmat',
  'density': 10.49,
  'mass': 107.87,
  'atomic_density': 0.0586},
 'Al2O3_sg167_Corundum.ncmat': {'short_name': 'Sapphire',
  'name': 'Corundum',
  'formula': 'Al2O3',
  'space_group': 167,
  'filename': 'Al2O3_sg167_Corundum.ncmat',
  'density': 3.95,
  'mass': 101.96,
  'atomic_density': 0.0233},
 'Al4C3_sg166_AluminiumCarbide.ncmat': {'short_name': 'Al4C3',
  'name': 'AluminiumCarbide',
  'formula': 'Al4C3',
  'space_group': 166,
  'filename': 'Al4C3_sg166_AluminiumCarbide.ncmat',
  'density': 2.99,
  'mass': 143.96,
  'atomic_density': 0.0125},
 'AlN_sg186_AluminumNitride.ncmat': {'short_name': 'Aluminum Nitride',
  'name': 'AluminumNitride',
  'formula': 'AlN',
  'space_group': 186,
  'filename': 'AlN_sg186_AluminumNitride.ncmat',
  'density': 3.26,
  'mass': 40.99,
  'atomic_density': 0.0479},
 'Al_sg225_Aluminum.ncmat': {'short_name': 'Aluminum',
  'name': 'Aluminum',
  'formula': 'Al',
  'space_group': 225,
  'filename': 'Al_sg225_Aluminum.ncmat',
  'density': 2.7,
  'mass': 26.98,
  'atomic_density': 0.0603},
 'Au_sg225_Gold.ncmat': {'short_name': 'Gold',
  'name': 'Gold',
  'formula': 'Au',
  'space_group': 225,
  'filename': 'Au_sg225_Gold.ncmat',
  'density': 19.32,
  'mass': 196.97,
  'atomic_density': 0.0591},
 'BaF2_sg225_BariumFluoride.ncmat': {'short_name': 'Barium Fluoride',
  'name': 'BariumFluoride',
  'formula': 'BaF2',
  'space_group': 225,
  'filename': 'BaF2_sg225_BariumFluoride.ncmat',
  'density': 4.89,
  'mass': 175.32,
  'atomic_density': 0.0168},
 'BaO_sg225_BariumOxide.ncmat': {'short_name': 'Barium Oxide',
  'name': 'BariumOxide',
  'formula': 'BaO',
  'space_group': 225,
  'filename': 'BaO_sg225_BariumOxide.ncmat',
  'density': 5.72,
  'mass': 153.33,
  'atomic_density': 0.0225},
 'Ba_sg229_Barium.ncmat': {'short_name': 'Barium',
  'name': 'Barium',
  'formula': 'Ba',
  'space_group': 229,
  'filename': 'Ba_sg229_Barium.ncmat',
  'density': 3.51,
  'mass': 137.33,
  'atomic_density': 0.0154},
 'Be2C_sg225_BerylliumCarbide.ncmat': {'short_name': 'Beryllium Carbide',
  'name': 'BerylliumCarbide',
  'formula': 'Be2C',
  'space_group': 225,
  'filename': 'Be2C_sg225_BerylliumCarbide.ncmat',
  'density': 1.9,
  'mass': 30.03,
  'atomic_density': 0.0381},
 'Be3N2_sg206_BerylliumNitride.ncmat': {'short_name': 'Beryllium Nitride',
  'name': 'BerylliumNitride',
  'formula': 'Be3N2',
  'space_group': 206,
  'filename': 'Be3N2_sg206_BerylliumNitride.ncmat',
  'density': 2.71,
  'mass': 55.05,
  'atomic_density': 0.0296},
 'BeF2_sg152_BerylliumFluoride.ncmat': {'short_name': 'Beryllium Fluoride',
  'name': 'BerylliumFluoride',
  'formula': 'BeF2',
  'space_group': 152,
  'filename': 'BeF2_sg152_BerylliumFluoride.ncmat',
  'density': 1.99,
  'mass': 47.01,
  'atomic_density': 0.0255},
 'BeH2_sg72_BerylliumHydride.ncmat': {'short_name': 'Beryllium Hydride',
  'name': 'BerylliumHydride',
  'formula': 'BeH2',
  'space_group': 72,
  'filename': 'BeH2_sg72_BerylliumHydride.ncmat',
  'density': 0.65,
  'mass': 11.03,
  'atomic_density': 0.0355},
 'BeO2H2-beta_sg19_BerylliumHydroxide.ncmat': {'short_name': 'Beryllium Hydroxide',
  'name': 'BerylliumHydroxide',
  'formula': 'BeO2H2-beta',
  'space_group': 19,
  'filename': 'BeO2H2-beta_sg19_BerylliumHydroxide.ncmat',
  'density': 1.92,
  'mass': 43.03,
  'atomic_density': 0.0269},
 'BeO_sg186_BerylliumOxide.ncmat': {'short_name': 'Beryllia',
  'name': 'BerylliumOxide',
  'formula': 'BeO',
  'space_group': 186,
  'filename': 'BeO_sg186_BerylliumOxide.ncmat',
  'density': 3.01,
  'mass': 25.01,
  'atomic_density': 0.0725},
 'Be_sg194_Beryllium.ncmat': {'short_name': 'Beryllium',
  'name': 'Beryllium',
  'formula': 'Be',
  'space_group': 194,
  'filename': 'Be_sg194_Beryllium.ncmat',
  'density': 1.85,
  'mass': 9.01,
  'atomic_density': 0.1236},
 'Bi2O3-beta_sg114_BismuthTrioxide.ncmat': {'short_name': 'Bismuth Trioxide',
  'name': 'BismuthTrioxide',
  'formula': 'Bi2O3-beta',
  'space_group': 114,
  'filename': 'Bi2O3-beta_sg114_BismuthTrioxide.ncmat',
  'density': 8.9,
  'mass': 465.96,
  'atomic_density': 0.0115},
 'BiF3-beta_sg62_BismuthTrifluoride.ncmat': {'short_name': 'Bismuth Trifluoride',
  'name': 'BismuthTrifluoride',
  'formula': 'BiF3-beta',
  'space_group': 62,
  'filename': 'BiF3-beta_sg62_BismuthTrifluoride.ncmat',
  'density': 5.8,
  'mass': 266.99,
  'atomic_density': 0.0131},
 'BiF5_sg87_BismuthPentafluoride.ncmat': {'short_name': 'Bismuth Pentafluoride',
  'name': 'BismuthPentafluoride',
  'formula': 'BiF5',
  'space_group': 87,
  'filename': 'BiF5_sg87_BismuthPentafluoride.ncmat',
  'density': 5.1,
  'mass': 304.97,
  'atomic_density': 0.0101},
 'BiO2_sg15_BismuthOxide.ncmat': {'short_name': 'Bismuth Oxide',
  'name': 'BismuthOxide',
  'formula': 'BiO2',
  'space_group': 15,
  'filename': 'BiO2_sg15_BismuthOxide.ncmat',
  'density': 8.9,
  'mass': 241.98,
  'atomic_density': 0.0221},
 'Bi_sg166_Bismuth.ncmat': {'short_name': 'Bi',
  'name': 'Bismuth',
  'formula': 'Bi',
  'space_group': 166,
  'filename': 'Bi_sg166_Bismuth.ncmat',
  'density': 9.78,
  'mass': 208.98,
  'atomic_density': 0.0282},
 'CaCO3_sg62_Aragonite.ncmat': {'short_name': 'Aragonite',
  'name': 'Aragonite',
  'formula': 'CaCO3',
  'space_group': 62,
  'filename': 'CaCO3_sg62_Aragonite.ncmat',
  'density': 2.93,
  'mass': 100.09,
  'atomic_density': 0.0176},
 'CaF2_sg225_CalciumFlouride.ncmat': {'short_name': 'Calcium Flouride',
  'name': 'CalciumFlouride',
  'formula': 'CaF2',
  'space_group': 225,
  'filename': 'CaF2_sg225_CalciumFlouride.ncmat',
  'density': 3.18,
  'mass': 78.07,
  'atomic_density': 0.0245},
 'Ca-gamma_sg229_Calcium-gamma.ncmat': {'short_name': 'Calcium',
  'name': 'Calcium-gamma',
  'formula': 'Ca-gamma',
  'space_group': 229,
  'filename': 'Ca-gamma_sg229_Calcium-gamma.ncmat',
  'density': 1.54,
  'mass': 40.08,
  'atomic_density': 0.0231},
 'CaH2_sg62_CalciumHydride.ncmat': {'short_name': 'Calcium Hydride',
  'name': 'CalciumHydride',
  'formula': 'CaH2',
  'space_group': 62,
  'filename': 'CaH2_sg62_CalciumHydride.ncmat',
  'density': 1.7,
  'mass': 42.09,
  'atomic_density': 0.0243},
 'CaOH2_sg164_CalciumHydroxide.ncmat': {'short_name': 'Portlandite',
  'density': 2.24,
  'mass': 74.09,
  'atomic_density': 0.0182,
  'formula': 'CaOH2',
  'filename': 'CaOH2_sg164_CalciumHydroxide.ncmat',
  'name': 'CalciumHydroxide',
  'space_group': 164},
 'CaO_sg225_CalciumOxide.ncmat': {'short_name': 'Lime',
  'density': 3.34,
  'mass': 56.08,
  'atomic_density': 0.0359,
  'formula': 'CaO',
  'filename': 'CaO_sg225_CalciumOxide.ncmat',
  'name': 'CalciumOxide',
  'space_group': 225},
 'Ca_sg225_Calcium.ncmat': {'short_name': 'Calcium',
  'density': 1.55,
  'mass': 40.08,
  'atomic_density': 0.0233,
  'formula': 'Ca',
  'filename': 'Ca_sg225_Calcium.ncmat',
  'name': 'Calcium',
  'space_group': 225},
 'CaZrO3_sg32_CalciumZirconate.ncmat': {'short_name': 'Calcium Zirconate',
  'density': 4.7,
  'mass': 179.3,
  'atomic_density': 0.0158,
  'formula': 'CaZrO3',
  'filename': 'CaZrO3_sg32_CalciumZirconate.ncmat',
  'name': 'CalciumZirconate',
  'space_group': 32},
 'C-diamond_sg227_Diamond.ncmat': {'short_name': 'Diamond',
  'density': 3.51,
  'mass': 12.01,
  'atomic_density': 0.176,
  'formula': 'C-diamond',
  'filename': 'C-diamond_sg227_Diamond.ncmat',
  'name': 'Diamond',
  'space_group': 227},
 'CeO2_sg225_CeriumOxide.ncmat': {'short_name': 'Ceria',
  'density': 7.21,
  'mass': 172.12,
  'atomic_density': 0.0252,
  'formula': 'CeO2',
  'filename': 'CeO2_sg225_CeriumOxide.ncmat',
  'name': 'CeriumOxide',
  'space_group': 225},
 'CF4-alpha_sg15_CarbonTetrafluoride.ncmat': {'short_name': 'Freon-14',
  'density': 1.96,
  'mass': 88.0,
  'atomic_density': 0.0134,
  'formula': 'CF4-alpha',
  'filename': 'CF4-alpha_sg15_CarbonTetrafluoride.ncmat',
  'name': 'CarbonTetrafluoride',
  'space_group': 15},
 'C-graphite_sg194_PyrolyticGraphite.ncmat': {'short_name': 'Graphite',
  'density': 2.26,
  'mass': 12.01,
  'atomic_density': 0.1133,
  'formula': 'C-graphite',
  'filename': 'C-graphite_sg194_PyrolyticGraphite.ncmat',
  'name': 'PyrolyticGraphite',
  'space_group': 194},
 'Cr_sg229_Chromium.ncmat': {'short_name': 'Chromium',
  'density': 7.19,
  'mass': 52.0,
  'atomic_density': 0.0833,
  'formula': 'Cr',
  'filename': 'Cr_sg229_Chromium.ncmat',
  'name': 'Chromium',
  'space_group': 229},
 'C_sg227_Diamond.nxs': {'short_name': 'Diamond',
  'density': 3.51,
  'mass': 12.01,
  'atomic_density': 0.176,
  'formula': 'C',
  'filename': 'C_sg227_Diamond.nxs',
  'name': 'Diamond.nxs',
  'space_group': 227},
 'Cu2O_sg224_Cuprite.ncmat': {'short_name': 'Cuprite',
  'density': 6.0,
  'mass': 143.09,
  'atomic_density': 0.0253,
  'formula': 'Cu2O',
  'filename': 'Cu2O_sg224_Cuprite.ncmat',
  'name': 'Cuprite',
  'space_group': 224},
 'Cu_sg225_Copper.ncmat': {'short_name': 'Copper',
  'density': 8.96,
  'mass': 63.55,
  'atomic_density': 0.0849,
  'formula': 'Cu',
  'filename': 'Cu_sg225_Copper.ncmat',
  'name': 'Copper',
  'space_group': 225},
 'Dy2O3_sg206_DysprosiumOxide.ncmat': {'short_name': 'Dysprosium Oxide',
  'density': 7.81,
  'mass': 373.0,
  'atomic_density': 0.0126,
  'formula': 'Dy2O3',
  'filename': 'Dy2O3_sg206_DysprosiumOxide.ncmat',
  'name': 'DysprosiumOxide',
  'space_group': 206},
 'Fe-alpha_sg229_AlphaIron.ncmat': {'short_name': 'Alpha-Iron',
  'density': 7.87,
  'mass': 55.85,
  'atomic_density': 0.0849,
  'formula': 'Fe-alpha',
  'filename': 'Fe-alpha_sg229_AlphaIron.ncmat',
  'name': 'AlphaIron',
  'space_group': 229},
 'Fe-gamma_sg225_GammaIron.ncmat': {'short_name': 'Gamma-Iron',
  'density': 7.87,
  'mass': 55.85,
  'atomic_density': 0.0849,
  'formula': 'Fe-gamma',
  'filename': 'Fe-gamma_sg225_GammaIron.ncmat',
  'name': 'GammaIron',
  'space_group': 225},
 'GaN_sg186_GalliumNitride.ncmat': {'short_name': 'Gallium Nitride',
  'density': 6.15,
  'mass': 83.73,
  'atomic_density': 0.0442,
  'formula': 'GaN',
  'filename': 'GaN_sg186_GalliumNitride.ncmat',
  'name': 'GalliumNitride',
  'space_group': 186},
 'GaP_sg216_GalliumPhosphide.ncmat': {'short_name': 'Gallium Phosphide',
  'density': 4.13,
  'mass': 100.7,
  'atomic_density': 0.0247,
  'formula': 'GaP',
  'filename': 'GaP_sg216_GalliumPhosphide.ncmat',
  'name': 'GalliumPhosphide',
  'space_group': 216},
 'GaSe_sg194_GalliumSelenide.ncmat': {'short_name': 'Gallium Selenide',
  'density': 5.03,
  'mass': 148.66,
  'atomic_density': 0.0204,
  'formula': 'GaSe',
  'filename': 'GaSe_sg194_GalliumSelenide.ncmat',
  'name': 'GalliumSelenide',
  'space_group': 194},
 'Ge3Bi4O12_sg220_BismuthGermanate.ncmat': {'short_name': 'Bismuth Germanate',
  'density': 7.13,
  'mass': 1245.09,
  'atomic_density': 0.0034,
  'formula': 'Ge3Bi4O12',
  'filename': 'Ge3Bi4O12_sg220_BismuthGermanate.ncmat',
  'name': 'BismuthGermanate',
  'space_group': 220},
 'Ge_sg227_Germanium.ncmat': {'short_name': 'Germanium',
  'density': 5.32,
  'mass': 72.63,
  'atomic_density': 0.0441,
  'formula': 'Ge',
  'filename': 'Ge_sg227_Germanium.ncmat',
  'name': 'Germanium',
  'space_group': 227},
 'GeTe_sg160_GermaniumTelluride.ncmat': {'short_name': 'Germanium Telluride',
  'density': 6.14,
  'mass': 200.23,
  'atomic_density': 0.0185,
  'formula': 'GeTe',
  'filename': 'GeTe_sg160_GermaniumTelluride.ncmat',
  'name': 'GermaniumTelluride',
  'space_group': 160},
 'HfO2_sg14_HafniumOxide.ncmat': {'short_name': 'Hafnia',
  'density': 9.68,
  'mass': 210.49,
  'atomic_density': 0.0277,
  'formula': 'HfO2',
  'filename': 'HfO2_sg14_HafniumOxide.ncmat',
  'name': 'HafniumOxide',
  'space_group': 14},
 'Ho2O3_sg206_HolmiumOxide.ncmat': {'short_name': 'Holmium Oxide',
  'density': 8.41,
  'mass': 377.86,
  'atomic_density': 0.0134,
  'formula': 'Ho2O3',
  'filename': 'Ho2O3_sg206_HolmiumOxide.ncmat',
  'name': 'HolmiumOxide',
  'space_group': 206},
 'KBr_sg225_PotassiumBromide.ncmat': {'short_name': 'Potassium Bromide',
  'density': 2.75,
  'mass': 119.0,
  'atomic_density': 0.0139,
  'formula': 'KBr',
  'filename': 'KBr_sg225_PotassiumBromide.ncmat',
  'name': 'PotassiumBromide',
  'space_group': 225},
 'KF_sg225_PotassiumFlouride.ncmat': {'short_name': 'Potassium Fluoride',
  'density': 2.48,
  'mass': 58.1,
  'atomic_density': 0.0257,
  'formula': 'KF',
  'filename': 'KF_sg225_PotassiumFlouride.ncmat',
  'name': 'PotassiumFlouride',
  'space_group': 225},
 'KOH_sg4_PotassiumHydroxide.ncmat': {'short_name': 'Potassium Hydroxide',
  'density': 2.04,
  'mass': 56.11,
  'atomic_density': 0.0219,
  'formula': 'KOH',
  'filename': 'KOH_sg4_PotassiumHydroxide.ncmat',
  'name': 'PotassiumHydroxide',
  'space_group': 4},
 'K_sg229_Potassium.ncmat': {'short_name': 'Potassium',
  'density': 0.86,
  'mass': 39.1,
  'atomic_density': 0.0132,
  'formula': 'K',
  'filename': 'K_sg229_Potassium.ncmat',
  'name': 'Potassium',
  'space_group': 229},
 'La2O3_sg164_LanthanumOxide.ncmat': {'short_name': 'Lanthanum Oxide',
  'density': 6.51,
  'mass': 325.81,
  'atomic_density': 0.012,
  'formula': 'La2O3',
  'filename': 'La2O3_sg164_LanthanumOxide.ncmat',
  'name': 'LanthanumOxide',
  'space_group': 164},
 'LaBr3_sg176_LanthanumBromide.ncmat': {'short_name': 'Lanthanum Bromide',
  'density': 5.06,
  'mass': 379.65,
  'atomic_density': 0.008,
  'formula': 'LaBr3',
  'filename': 'LaBr3_sg176_LanthanumBromide.ncmat',
  'name': 'LanthanumBromide',
  'space_group': 176},
 'Li2O_sg225_LithiumOxide.ncmat': {'short_name': 'Lithium Oxide',
  'density': 2.01,
  'mass': 29.88,
  'atomic_density': 0.0405,
  'formula': 'Li2O',
  'filename': 'Li2O_sg225_LithiumOxide.ncmat',
  'name': 'LithiumOxide',
  'space_group': 225},
 'Li3N_sg191_LithiumNitride.ncmat': {'short_name': 'Lithium Nitride',
  'density': 1.27,
  'mass': 34.83,
  'atomic_density': 0.022,
  'formula': 'Li3N',
  'filename': 'Li3N_sg191_LithiumNitride.ncmat',
  'name': 'LithiumNitride',
  'space_group': 191},
 'LiF_sg225_LithiumFlouride.ncmat': {'short_name': 'Lithium Fluoride',
  'density': 2.64,
  'mass': 25.94,
  'atomic_density': 0.0613,
  'formula': 'LiF',
  'filename': 'LiF_sg225_LithiumFlouride.ncmat',
  'name': 'LithiumFlouride',
  'space_group': 225},
 'LiH_sg225_LithiumHydride.ncmat': {'short_name': 'Lithium Hydride',
  'density': 0.78,
  'mass': 7.95,
  'atomic_density': 0.0591,
  'formula': 'LiH',
  'filename': 'LiH_sg225_LithiumHydride.ncmat',
  'name': 'LithiumHydride',
  'space_group': 225},
 'Lu2O3_sg206_LutetiumOxide.ncmat': {'short_name': 'Lutetium Oxide',
  'density': 9.42,
  'mass': 397.94,
  'atomic_density': 0.0143,
  'formula': 'Lu2O3',
  'filename': 'Lu2O3_sg206_LutetiumOxide.ncmat',
  'name': 'LutetiumOxide',
  'space_group': 206},
 'Mg2SiO4_sg62_MagnesiumSilicate.ncmat': {'short_name': 'Forsterite',
  'density': 3.21,
  'mass': 140.69,
  'atomic_density': 0.0137,
  'formula': 'Mg2SiO4',
  'filename': 'Mg2SiO4_sg62_MagnesiumSilicate.ncmat',
  'name': 'MagnesiumSilicate',
  'space_group': 62},
 'MgAl2O4_sg227_MagnesiumAluminateSpinel.ncmat': {'short_name': 'Spinel',
  'density': 3.58,
  'mass': 142.27,
  'atomic_density': 0.0152,
  'formula': 'MgAl2O4',
  'filename': 'MgAl2O4_sg227_MagnesiumAluminateSpinel.ncmat',
  'name': 'MagnesiumAluminateSpinel',
  'space_group': 227},
 'MgCO3_sg167_MagnesiumCarbonate.ncmat': {'short_name': 'Magnesite',
  'density': 3.01,
  'mass': 84.31,
  'atomic_density': 0.0215,
  'formula': 'MgCO3',
  'filename': 'MgCO3_sg167_MagnesiumCarbonate.ncmat',
  'name': 'MagnesiumCarbonate',
  'space_group': 167},
 'MgD2_sg136_MagnesiumDeuteride.ncmat': {'short_name': 'Magnesium Deuteride',
  'density': 1.45,
  'mass': 28.03,
  'atomic_density': 0.0312,
  'formula': 'MgD2',
  'filename': 'MgD2_sg136_MagnesiumDeuteride.ncmat',
  'name': 'MagnesiumDeuteride',
  'space_group': 136},
 'MgF2_sg136_MagnesiumFlouride.ncmat': {'short_name': 'Magnesium Fluoride',
  'density': 3.15,
  'mass': 62.3,
  'atomic_density': 0.0304,
  'formula': 'MgF2',
  'filename': 'MgF2_sg136_MagnesiumFlouride.ncmat',
  'name': 'MagnesiumFlouride',
  'space_group': 136},
 'MgH2_sg136_MagnesiumHydride.ncmat': {'short_name': 'Magnesium Hydride',
  'density': 1.45,
  'mass': 26.32,
  'atomic_density': 0.0332,
  'formula': 'MgH2',
  'filename': 'MgH2_sg136_MagnesiumHydride.ncmat',
  'name': 'MagnesiumHydride',
  'space_group': 136},
 'MgOH2_sg164_MagnesiumHydroxide.ncmat': {'short_name': 'Brucite',
  'density': 2.34,
  'mass': 58.32,
  'atomic_density': 0.0242,
  'formula': 'MgOH2',
  'filename': 'MgOH2_sg164_MagnesiumHydroxide.ncmat',
  'name': 'MagnesiumHydroxide',
  'space_group': 164},
 'MgO_sg225_Periclase.ncmat': {'short_name': 'Periclase',
  'density': 3.58,
  'mass': 40.3,
  'atomic_density': 0.0535,
  'formula': 'MgO',
  'filename': 'MgO_sg225_Periclase.ncmat',
  'name': 'Periclase',
  'space_group': 225},
 'Mg_sg194_Magnesium.ncmat': {'short_name': 'Magnesium',
  'density': 1.74,
  'mass': 24.31,
  'atomic_density': 0.0431,
  'formula': 'Mg',
  'filename': 'Mg_sg194_Magnesium.ncmat',
  'name': 'Magnesium',
  'space_group': 194},
 'Mo_sg229_Molybdenum.ncmat': {'short_name': 'Molybdenum',
  'density': 10.22,
  'mass': 95.95,
  'atomic_density': 0.0641,
  'formula': 'Mo',
  'filename': 'Mo_sg229_Molybdenum.ncmat',
  'name': 'Molybdenum',
  'space_group': 229},
 'Na4Si3Al3O12Cl_sg218_Sodalite.ncmat': {'short_name': 'Sodalite',
  'density': 2.27,
  'mass': 474.4,
  'atomic_density': 0.0029,
  'formula': 'Na4Si3Al3O12Cl',
  'filename': 'Na4Si3Al3O12Cl_sg218_Sodalite.ncmat',
  'name': 'Sodalite',
  'space_group': 218},
 'NaAlH4_sg88_SodiumAluminiumHydride.ncmat': {'short_name': 'Sodium Alanate',
  'density': 1.28,
  'mass': 54.0,
  'atomic_density': 0.0143,
  'formula': 'NaAlH4',
  'filename': 'NaAlH4_sg88_SodiumAluminiumHydride.ncmat',
  'name': 'SodiumAluminiumHydride',
  'space_group': 88},
 'NaBrO3_sg198_SodiumBromate.ncmat': {'short_name': 'Sodium Bromate',
  'density': 3.34,
  'mass': 150.89,
  'atomic_density': 0.0133,
  'formula': 'NaBrO3',
  'filename': 'NaBrO3_sg198_SodiumBromate.ncmat',
  'name': 'SodiumBromate',
  'space_group': 198},
 'NaBr_sg225_SodiumBromide.ncmat': {'short_name': 'Sodium Bromide',
  'density': 3.21,
  'mass': 102.89,
  'atomic_density': 0.0188,
  'formula': 'NaBr',
  'filename': 'NaBr_sg225_SodiumBromide.ncmat',
  'name': 'SodiumBromide',
  'space_group': 225},
 'NaCl_sg225_SodiumChloride.ncmat': {'short_name': 'Halite',
  'density': 2.16,
  'mass': 58.44,
  'atomic_density': 0.0223,
  'formula': 'NaCl',
  'filename': 'NaCl_sg225_SodiumChloride.ncmat',
  'name': 'SodiumChloride',
  'space_group': 225},
 'NaF_sg225_SodiumFlouride.ncmat': {'short_name': 'Sodium Fluoride',
  'density': 2.56,
  'mass': 41.99,
  'atomic_density': 0.0367,
  'formula': 'NaF',
  'filename': 'NaF_sg225_SodiumFlouride.ncmat',
  'name': 'SodiumFlouride',
  'space_group': 225},
 'NaI_sg225_SodiumIodide.ncmat': {'short_name': 'Sodium Iodide',
  'density': 3.67,
  'mass': 149.89,
  'atomic_density': 0.0147,
  'formula': 'NaI',
  'filename': 'NaI_sg225_SodiumIodide.ncmat',
  'name': 'SodiumIodide',
  'space_group': 225},
 'NaMgH3_sg62_SodiumMagnesiumHydride.ncmat': {'short_name': 'Sodium Magnesium Hydride',
  'density': 1.51,
  'mass': 54.33,
  'atomic_density': 0.0167,
  'formula': 'NaMgH3',
  'filename': 'NaMgH3_sg62_SodiumMagnesiumHydride.ncmat',
  'name': 'SodiumMagnesiumHydride',
  'space_group': 62},
 'NaOH_sg63_SodiumHydroxide.ncmat': {'short_name': 'Sodium Hydroxide',
  'density': 2.13,
  'mass': 40.0,
  'atomic_density': 0.0321,
  'formula': 'NaOH',
  'filename': 'NaOH_sg63_SodiumHydroxide.ncmat',
  'name': 'SodiumHydroxide',
  'space_group': 63},
 'Na_sg229_Sodium.ncmat': {'short_name': 'Sodium',
  'density': 0.97,
  'mass': 22.99,
  'atomic_density': 0.0254,
  'formula': 'Na',
  'filename': 'Na_sg229_Sodium.ncmat',
  'name': 'Sodium',
  'space_group': 229},
 'Nb_sg229_Niobium.ncmat': {'short_name': 'Niobium',
  'density': 8.57,
  'mass': 92.91,
  'atomic_density': 0.0555,
  'formula': 'Nb',
  'filename': 'Nb_sg229_Niobium.ncmat',
  'name': 'Niobium',
  'space_group': 229},
 'Nd2O3_sg164_NeodymiumOxide.ncmat': {'short_name': 'Neodymium Oxide',
  'density': 7.24,
  'mass': 336.48,
  'atomic_density': 0.013,
  'formula': 'Nd2O3',
  'filename': 'Nd2O3_sg164_NeodymiumOxide.ncmat',
  'name': 'NeodymiumOxide',
  'space_group': 164},
 'Ni_sg225_Nickel.ncmat': {'short_name': 'Nickel',
  'density': 8.9,
  'mass': 58.69,
  'atomic_density': 0.0913,
  'formula': 'Ni',
  'filename': 'Ni_sg225_Nickel.ncmat',
  'name': 'Nickel',
  'space_group': 225},
 'P2O5_sg62_PhosphorusPentoxide.ncmat': {'short_name': 'Phosphorus Pentoxide',
  'density': 2.39,
  'mass': 141.94,
  'atomic_density': 0.0101,
  'formula': 'P2O5',
  'filename': 'P2O5_sg62_PhosphorusPentoxide.ncmat',
  'name': 'PhosphorusPentoxide',
  'space_group': 62},
 'Pb3O4_sg135_LeadOxide.ncmat': {'short_name': 'Red Lead',
  'density': 8.92,
  'mass': 685.6,
  'atomic_density': 0.0078,
  'formula': 'Pb3O4',
  'filename': 'Pb3O4_sg135_LeadOxide.ncmat',
  'name': 'LeadOxide',
  'space_group': 135},
 'PbCO3_sg62_LeadCarbonate.ncmat': {'short_name': 'Cerussite',
  'density': 6.58,
  'mass': 267.21,
  'atomic_density': 0.0148,
  'formula': 'PbCO3',
  'filename': 'PbCO3_sg62_LeadCarbonate.ncmat',
  'name': 'LeadCarbonate',
  'space_group': 62},
 'PbF2_sg225_LeadFlouride.ncmat': {'short_name': 'Lead Fluoride',
  'density': 8.24,
  'mass': 245.2,
  'atomic_density': 0.0202,
  'formula': 'PbF2',
  'filename': 'PbF2_sg225_LeadFlouride.ncmat',
  'name': 'LeadFlouride',
  'space_group': 225},
 'PbF4_sg139_LeadTetrafluoride.ncmat': {'short_name': 'Lead Tetrafluoride',
  'density': 5.19,
  'mass': 283.19,
  'atomic_density': 0.011,
  'formula': 'PbF4',
  'filename': 'PbF4_sg139_LeadTetrafluoride.ncmat',
  'name': 'LeadTetrafluoride',
  'space_group': 139},
 'PbO-alpha_sg129_AlphaLeadMonoxide.ncmat': {'short_name': 'Litharge',
  'density': 9.53,
  'mass': 223.2,
  'atomic_density': 0.0257,
  'formula': 'PbO-alpha',
  'filename': 'PbO-alpha_sg129_AlphaLeadMonoxide.ncmat',
  'name': 'AlphaLeadMonoxide',
  'space_group': 129},
 'PbO-beta_sg57_BetaLeadMonoxide.ncmat': {'short_name': 'Massicot',
  'density': 9.53,
  'mass': 223.2,
  'atomic_density': 0.0257,
  'formula': 'PbO-beta',
  'filename': 'PbO-beta_sg57_BetaLeadMonoxide.ncmat',
  'name': 'BetaLeadMonoxide',
  'space_group': 57},
 'Pb_sg225_Lead.ncmat': {'short_name': 'Lead',
  'density': 11.34,
  'mass': 207.2,
  'atomic_density': 0.033,
  'formula': 'Pb',
  'filename': 'Pb_sg225_Lead.ncmat',
  'name': 'Lead',
  'space_group': 225},
 'PbS_sg225_LeadSulfide.ncmat': {'short_name': 'Galena',
  'density': 7.6,
  'mass': 239.27,
  'atomic_density': 0.0191,
  'formula': 'PbS',
  'filename': 'PbS_sg225_LeadSulfide.ncmat',
  'name': 'LeadSulfide',
  'space_group': 225},
 'Pd_sg225_Palladium.ncmat': {'short_name': 'Palladium',
  'density': 12.02,
  'mass': 106.42,
  'atomic_density': 0.068,
  'formula': 'Pd',
  'filename': 'Pd_sg225_Palladium.ncmat',
  'name': 'Palladium',
  'space_group': 225},
 'Pr2O3_sg164_PraseodymiumOxide.ncmat': {'short_name': 'Praseodymium Oxide',
  'density': 6.88,
  'mass': 329.81,
  'atomic_density': 0.0126,
  'formula': 'Pr2O3',
  'filename': 'Pr2O3_sg164_PraseodymiumOxide.ncmat',
  'name': 'PraseodymiumOxide',
  'space_group': 164},
 'Pt_sg225_Platinum.ncmat': {'short_name': 'Platinum',
  'density': 21.45,
  'mass': 195.08,
  'atomic_density': 0.0662,
  'formula': 'Pt',
  'filename': 'Pt_sg225_Platinum.ncmat',
  'name': 'Platinum',
  'space_group': 225},
 'Rb_sg229_Rubidium.ncmat': {'short_name': 'Rubidium',
  'density': 1.53,
  'mass': 85.47,
  'atomic_density': 0.0108,
  'formula': 'Rb',
  'filename': 'Rb_sg229_Rubidium.ncmat',
  'name': 'Rubidium',
  'space_group': 229},
 'Sc2O3_sg206_ScandiumOxide.ncmat': {'short_name': 'Scandium Oxide',
  'density': 3.86,
  'mass': 137.91,
  'atomic_density': 0.0169,
  'formula': 'Sc2O3',
  'filename': 'Sc2O3_sg206_ScandiumOxide.ncmat',
  'name': 'ScandiumOxide',
  'space_group': 206},
 'Sc_sg194_Scandium.ncmat': {'short_name': 'Scandium',
  'density': 2.99,
  'mass': 44.96,
  'atomic_density': 0.04,
  'formula': 'Sc',
  'filename': 'Sc_sg194_Scandium.ncmat',
  'name': 'Scandium',
  'space_group': 194},
 'Si3N4-beta_sg176_SiliconNitride.ncmat': {'short_name': 'Silicon Nitride',
  'density': 3.2,
  'mass': 140.28,
  'atomic_density': 0.0137,
  'formula': 'Si3N4-beta',
  'filename': 'Si3N4-beta_sg176_SiliconNitride.ncmat',
  'name': 'SiliconNitride',
  'space_group': 176},
 'SiC-alpha_sg186_AlphaSiliconCarbide.ncmat': {'short_name': 'Moissanite',
  'density': 3.21,
  'mass': 40.1,
  'atomic_density': 0.0482,
  'formula': 'SiC-alpha',
  'filename': 'SiC-alpha_sg186_AlphaSiliconCarbide.ncmat',
  'name': 'AlphaSiliconCarbide',
  'space_group': 186},
 'SiC-beta_sg216_BetaSiliconCarbide.ncmat': {'short_name': 'Beta Silicon Carbide',
  'density': 3.21,
  'mass': 40.1,
  'atomic_density': 0.0482,
  'formula': 'SiC-beta',
  'filename': 'SiC-beta_sg216_BetaSiliconCarbide.ncmat',
  'name': 'BetaSiliconCarbide',
  'space_group': 216},
 'SiLu2O5_sg15_SiliconLutetiumOxide.ncmat': {'short_name': 'Silicon Lutetium Oxide',
  'density': 6.21,
  'mass': 443.96,
  'atomic_density': 0.0084,
  'formula': 'SiLu2O5',
  'filename': 'SiLu2O5_sg15_SiliconLutetiumOxide.ncmat',
  'name': 'SiliconLutetiumOxide',
  'space_group': 15},
 'SiO2-alpha_sg154_AlphaQuartz.ncmat': {'short_name': 'Quartz',
  'density': 2.65,
  'mass': 60.08,
  'atomic_density': 0.0266,
  'formula': 'SiO2-alpha',
  'filename': 'SiO2-alpha_sg154_AlphaQuartz.ncmat',
  'name': 'AlphaQuartz',
  'space_group': 154},
 'SiO2-beta_sg180_BetaQuartz.ncmat': {'short_name': 'Beta Quartz',
  'density': 2.53,
  'mass': 60.08,
  'atomic_density': 0.0254,
  'formula': 'SiO2-beta',
  'filename': 'SiO2-beta_sg180_BetaQuartz.ncmat',
  'name': 'BetaQuartz',
  'space_group': 180},
 'Si_sg227_Silicon.ncmat': {'short_name': 'Silicon',
  'density': 2.33,
  'mass': 28.09,
  'atomic_density': 0.05,
  'formula': 'Si',
  'filename': 'Si_sg227_Silicon.ncmat',
  'name': 'Silicon',
  'space_group': 227},
 'SiY2O5_sg15_SiliconYttriumOxide.ncmat': {'short_name': 'Silicon Yttrium Oxide',
  'density': 4.15,
  'mass': 273.92,
  'atomic_density': 0.0091,
  'formula': 'SiY2O5',
  'filename': 'SiY2O5_sg15_SiliconYttriumOxide.ncmat',
  'name': 'SiliconYttriumOxide',
  'space_group': 15},
 'SnF2_sg15_Tin-II-Flouride.ncmat': {'short_name': 'Tin(II) Fluoride',
  'density': 4.57,
  'mass': 156.71,
  'atomic_density': 0.0176,
  'formula': 'SnF2',
  'filename': 'SnF2_sg15_Tin-II-Flouride.ncmat',
  'name': 'Tin-II-Flouride',
  'space_group': 15},
 'SnF4_sg139_Tin-IV-flouride.ncmat': {'short_name': 'Tin(IV) Fluoride',
  'density': 4.78,
  'mass': 194.7,
  'atomic_density': 0.0148,
  'formula': 'SnF4',
  'filename': 'SnF4_sg139_Tin-IV-flouride.ncmat',
  'name': 'Tin-IV-flouride',
  'space_group': 139},
 'Sn_sg141_Tin.ncmat': {'short_name': 'Tin',
  'density': 7.31,
  'mass': 118.71,
  'atomic_density': 0.0371,
  'formula': 'Sn',
  'filename': 'Sn_sg141_Tin.ncmat',
  'name': 'Tin',
  'space_group': 141},
 'SrF2_sg225_StrontiumFluoride.ncmat': {'short_name': 'Strontium Fluoride',
  'density': 4.24,
  'mass': 125.62,
  'atomic_density': 0.0203,
  'formula': 'SrF2',
  'filename': 'SrF2_sg225_StrontiumFluoride.ncmat',
  'name': 'StrontiumFluoride',
  'space_group': 225},
 'SrH2_sg62_StrontiumHydride.ncmat': {'short_name': 'Strontium Hydride',
  'density': 3.26,
  'mass': 89.64,
  'atomic_density': 0.0219,
  'formula': 'SrH2',
  'filename': 'SrH2_sg62_StrontiumHydride.ncmat',
  'name': 'StrontiumHydride',
  'space_group': 62},
 'Sr_sg225_Strontium.ncmat': {'short_name': 'Strontium',
  'density': 2.64,
  'mass': 87.62,
  'atomic_density': 0.0181,
  'formula': 'Sr',
  'filename': 'Sr_sg225_Strontium.ncmat',
  'name': 'Strontium',
  'space_group': 225},
 'SrTiO3_sg221_StrontiumTitanate.ncmat': {'short_name': 'Strontium Titanate',
  'density': 5.12,
  'mass': 183.49,
  'atomic_density': 0.0168,
  'formula': 'SrTiO3',
  'filename': 'SrTiO3_sg221_StrontiumTitanate.ncmat',
  'name': 'StrontiumTitanate',
  'space_group': 221},
 'Th3N4_sg166_ThoriumNitride.ncmat': {'short_name': 'Thorium Nitride',
  'density': 9.5,
  'mass': 754.11,
  'atomic_density': 0.0076,
  'formula': 'Th3N4',
  'filename': 'Th3N4_sg166_ThoriumNitride.ncmat',
  'name': 'ThoriumNitride',
  'space_group': 166},
 'ThO2_sg225_ThoriumDioxide.ncmat': {'short_name': 'Thorianite',
  'density': 10.0,
  'mass': 264.04,
  'atomic_density': 0.0228,
  'formula': 'ThO2',
  'filename': 'ThO2_sg225_ThoriumDioxide.ncmat',
  'name': 'ThoriumDioxide',
  'space_group': 225},
 'ThSiO4_sg14_Huttonite.ncmat': {'short_name': 'Huttonite',
  'density': 6.7,
  'mass': 324.12,
  'atomic_density': 0.0124,
  'formula': 'ThSiO4',
  'filename': 'ThSiO4_sg14_Huttonite.ncmat',
  'name': 'Huttonite',
  'space_group': 14},
 'TiO2-anatase_sg141_Anatase.ncmat': {'short_name': 'Anatase',
  'density': 3.89,
  'mass': 79.87,
  'atomic_density': 0.0293,
  'formula': 'TiO2-anatase',
  'filename': 'TiO2-anatase_sg141_Anatase.ncmat',
  'name': 'Anatase',
  'space_group': 141},
 'TiO2-rutile_sg136_Rutile.ncmat': {'short_name': 'Rutile',
  'density': 4.23,
  'mass': 79.87,
  'atomic_density': 0.0319,
  'formula': 'TiO2-rutile',
  'filename': 'TiO2-rutile_sg136_Rutile.ncmat',
  'name': 'Rutile',
  'space_group': 136},
 'Ti_sg194_Titanium.ncmat': {'short_name': 'Titanium',
  'density': 4.51,
  'mass': 47.87,
  'atomic_density': 0.0567,
  'formula': 'Ti',
  'filename': 'Ti_sg194_Titanium.ncmat',
  'name': 'Titanium',
  'space_group': 194},
 'TlBr_sg221_ThaliumBromide.ncmat': {'short_name': 'Thallium Bromide',
  'density': 7.56,
  'mass': 284.3,
  'atomic_density': 0.016,
  'formula': 'TlBr',
  'filename': 'TlBr_sg221_ThaliumBromide.ncmat',
  'name': 'ThaliumBromide',
  'space_group': 221},
 'Tm2O3_sg206_ThuliumOxide.ncmat': {'short_name': 'Thulium Oxide',
  'density': 8.63,
  'mass': 385.87,
  'atomic_density': 0.0135,
  'formula': 'Tm2O3',
  'filename': 'Tm2O3_sg206_ThuliumOxide.ncmat',
  'name': 'ThuliumOxide',
  'space_group': 206},
 'UF6_sg62_UraniumHexaflouride.ncmat': {'short_name': 'Uranium Hexafluoride',
  'density': 5.09,
  'mass': 352.02,
  'atomic_density': 0.0087,
  'formula': 'UF6',
  'filename': 'UF6_sg62_UraniumHexaflouride.ncmat',
  'name': 'UraniumHexaflouride',
  'space_group': 62},
 'UO2_sg225_UraniumDioxide.ncmat': {'short_name': 'Uraninite',
  'density': 10.97,
  'mass': 270.03,
  'atomic_density': 0.0245,
  'formula': 'UO2',
  'filename': 'UO2_sg225_UraniumDioxide.ncmat',
  'name': 'UraniumDioxide',
  'space_group': 225},
 'V_sg229_Vanadium.ncmat': {'short_name': 'Vanadium',
  'density': 6.11,
  'mass': 50.94,
  'atomic_density': 0.0722,
  'formula': 'V',
  'filename': 'V_sg229_Vanadium.ncmat',
  'name': 'Vanadium',
  'space_group': 229},
 'W_sg229_Tungsten.ncmat': {'short_name': 'Tungsten',
  'density': 19.25,
  'mass': 183.84,
  'atomic_density': 0.0631,
  'formula': 'W',
  'filename': 'W_sg229_Tungsten.ncmat',
  'name': 'Tungsten',
  'space_group': 229},
 'Y2O3_sg206_YttriumOxide.ncmat': {'short_name': 'Yttria',
  'density': 5.01,
  'mass': 225.81,
  'atomic_density': 0.0134,
  'formula': 'Y2O3',
  'filename': 'Y2O3_sg206_YttriumOxide.ncmat',
  'name': 'YttriumOxide',
  'space_group': 206},
 'Y3Al5O12_sg230_YttriumAluminiumGarnet.ncmat': {'short_name': 'YAG',
  'density': 4.56,
  'mass': 593.7,
  'atomic_density': 0.0046,
  'formula': 'Y3Al5O12',
  'filename': 'Y3Al5O12_sg230_YttriumAluminiumGarnet.ncmat',
  'name': 'YttriumAluminiumGarnet',
  'space_group': 230},
 'YAlO3_sg62_YttriumOrthoaluminate.ncmat': {'short_name': 'YAP',
  'density': 5.35,
  'mass': 163.9,
  'atomic_density': 0.0197,
  'formula': 'YAlO3',
  'filename': 'YAlO3_sg62_YttriumOrthoaluminate.ncmat',
  'name': 'YttriumOrthoaluminate',
  'space_group': 62},
 'Y_sg194_Yttrium.ncmat': {'short_name': 'Yttrium',
  'density': 4.47,
  'mass': 88.91,
  'atomic_density': 0.0303,
  'formula': 'Y',
  'filename': 'Y_sg194_Yttrium.ncmat',
  'name': 'Yttrium',
  'space_group': 194},
 'ZnF2_sg136_ZincFlouride.ncmat': {'short_name': 'Zinc Fluoride',
  'density': 4.95,
  'mass': 103.41,
  'atomic_density': 0.0288,
  'formula': 'ZnF2',
  'filename': 'ZnF2_sg136_ZincFlouride.ncmat',
  'name': 'ZincFlouride',
  'space_group': 136},
 'ZnO_sg186_ZincOxide.ncmat': {'short_name': 'Zincite',
  'density': 5.61,
  'mass': 81.39,
  'atomic_density': 0.0415,
  'formula': 'ZnO',
  'filename': 'ZnO_sg186_ZincOxide.ncmat',
  'name': 'ZincOxide',
  'space_group': 186},
 'Zn_sg194_Zinc.ncmat': {'short_name': 'Zinc',
  'density': 7.13,
  'mass': 65.39,
  'atomic_density': 0.0657,
  'formula': 'Zn',
  'filename': 'Zn_sg194_Zinc.ncmat',
  'name': 'Zinc',
  'space_group': 194},
 'ZnS-sphalerite_sg216_ZincSulfide.ncmat': {'short_name': 'Sphalerite',
  'density': 4.09,
  'mass': 97.46,
  'atomic_density': 0.0253,
  'formula': 'ZnS-sphalerite',
  'filename': 'ZnS-sphalerite_sg216_ZincSulfide.ncmat',
  'name': 'ZincSulfide',
  'space_group': 216},
 'ZrF4-beta_sg84_BetaZirconiumTetrafluoride.ncmat': {'short_name': 'Zirconium Tetrafluoride',
  'density': 4.43,
  'mass': 167.22,
  'atomic_density': 0.016,
  'formula': 'ZrF4-beta',
  'filename': 'ZrF4-beta_sg84_BetaZirconiumTetrafluoride.ncmat',
  'name': 'BetaZirconiumTetrafluoride',
  'space_group': 84},
 'ZrO2_sg14_ZirconiumDioxide.ncmat': {'short_name': 'Baddeleyite',
  'density': 5.68,
  'mass': 123.22,
  'atomic_density': 0.0278,
  'formula': 'ZrO2',
  'filename': 'ZrO2_sg14_ZirconiumDioxide.ncmat',
  'name': 'ZirconiumDioxide',
  'space_group': 14},
 'ZrO2-tet_sg137_TetragonalZirconiumDioxide.ncmat': {'short_name': 'Tetragonal Zirconia',
  'density': 6.1,
  'mass': 123.22,
  'atomic_density': 0.0298,
  'formula': 'ZrO2-tet',
  'filename': 'ZrO2-tet_sg137_TetragonalZirconiumDioxide.ncmat',
  'name': 'TetragonalZirconiumDioxide',
  'space_group': 137},
 'Zr_sg194_Zirconium.ncmat': {'short_name': 'Zirconium',
  'density': 6.51,
  'mass': 91.22,
  'atomic_density': 0.043,
  'formula': 'Zr',
  'filename': 'Zr_sg194_Zirconium.ncmat',
  'name': 'Zirconium',
  'space_group': 194},
 'ZrSiO4_sg141_ZirconiumOrthosilicate.ncmat': {'short_name': 'Zircon',
  'density': 4.56,
  'mass': 183.31,
  'atomic_density': 0.015,
  'formula': 'ZrSiO4',
  'filename': 'ZrSiO4_sg141_ZirconiumOrthosilicate.ncmat',
  'name': 'ZirconiumOrthosilicate',
  'space_group': 141}}

materials["Fe_sg225_Iron-gamma.ncmat"] = materials["Fe-gamma_sg225_GammaIron.ncmat"]
materials["Fe_sg225_Iron-gamma.ncmat"]["filename"] = "Fe_sg225_Iron-gamma.ncmat"

materials["Fe_sg229_Iron-alpha.ncmat"] = materials["Fe-alpha_sg229_AlphaIron.ncmat"]
materials["Fe_sg229_Iron-alpha.ncmat"]["filename"] = "Fe_sg229_Iron-alpha.ncmat"


# add short_name keys to dictionary
new_keys = {}
for key in materials:
    new_keys[materials[key]["short_name"]] = materials[key]
materials.update(new_keys)